from __future__ import annotations

from typing import Protocol, Sequence

from .records import OutboxRecord, TaskOutcome, TaskRecord, ToolOperationRecord
from .serialization import JsonValue


class DurableStorage(Protocol):
    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def create_task(self, record: TaskRecord) -> None: ...
    async def accept_task(self, task: TaskRecord, outbox: Sequence[OutboxRecord]) -> None: ...
    async def get_task(self, task_id: str) -> TaskRecord | None: ...
    async def get_open_task(self, session_id: str) -> TaskRecord | None: ...
    async def replace_task(self, record: TaskRecord) -> None: ...
    async def replace_task_cas(self, record: TaskRecord, *, expected_revision: int) -> None: ...
    async def replace_task_with_outbox_cas(self, record: TaskRecord, outbox: Sequence[OutboxRecord], *, expected_revision: int) -> None: ...
    async def settle_assistant_with_tool_plan(self, task: TaskRecord, operations: Sequence[ToolOperationRecord], outbox: Sequence[OutboxRecord], *, expected_revision: int) -> None: ...
    async def scan_tasks(self, *, status: str | None = None, kind: str | None = None) -> list[TaskRecord]: ...
    async def create_tool_batch_intents(self, records: Sequence[ToolOperationRecord]) -> None: ...
    async def get_operation(self, operation_id: str) -> ToolOperationRecord | None: ...
    async def get_operations(self, ids: Sequence[str]) -> list[ToolOperationRecord]: ...
    async def create_or_replace_tool_effect_intent(self, operation: ToolOperationRecord, *, expected_status: str = "planned") -> None: ...
    async def settle_tool_operation(self, operation: ToolOperationRecord, outbox: OutboxRecord, *, expected_status: str) -> None: ...
    async def settle_operation(self, operation: ToolOperationRecord, outbox: OutboxRecord) -> None: ...
    async def scan_effect_pending_operations(self) -> list[ToolOperationRecord]: ...
    async def scan_pending_outbox(self, *, task_id: str | None = None, group_id: str | None = None) -> list[OutboxRecord]: ...
    async def mark_outbox_published(self, outbox_id: str, published_at: str) -> None: ...
    async def get_memo(self, operation_id: str, name: str) -> JsonValue | None: ...
    async def memo(self, operation_id: str, name: str, candidate: JsonValue) -> JsonValue: ...
    async def request_abort(self, task_id: str) -> TaskRecord: ...
    async def terminalize_task(self, task_id: str, outcome: TaskOutcome, updated_at: str) -> None: ...
